### ISSUE TITLE
Kondo crash on `PermissionDenied`

### ISSUE THREAD

**Issue by senden9** [tbillington/kondo#16]
Hi!

At the moment kondo crashes if it hits something it can't open. Maybe show some warning that folder/file `x` can not be analyzed and continue scanning.

I use version 0.2; build from git hash c2307fa0670baebdec9acf613385714cfc0ec052.

```
$ kondo -V
kondo 0.2.0

$ RUST_BACKTRACE=1 kondo
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 13, kind: PermissionDenied, message: "Permission denied" }', src/libcore/result.rs:1188:5
stack backtrace:
   0: backtrace::backtrace::libunwind::trace
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/libunwind.rs:88
   1: backtrace::backtrace::trace_unsynchronized
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.40/src/backtrace/mod.rs:66
   2: std::sys_common::backtrace::_print_fmt
             at src/libstd/sys_common/backtrace.rs:84
   3: <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt
             at src/libstd/sys_common/backtrace.rs:61
   4: core::fmt::write
             at src/libcore/fmt/mod.rs:1025
   5: std::io::Write::write_fmt
             at src/libstd/io/mod.rs:1426
   6: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:65
   7: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:50
   8: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:193
   9: std::panicking::default_hook
             at src/libstd/panicking.rs:210
  10: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:471
  11: rust_begin_unwind
             at src/libstd/panicking.rs:375
  12: core::panicking::panic_fmt
             at src/libcore/panicking.rs:84
  13: core::result::unwrap_failed
             at src/libcore/result.rs:1188
  14: kondo::check_file_exists
  15: <core::iter::adapters::FilterMap<I,F> as core::iter::traits::iterator::Iterator>::next
  16: <core::iter::adapters::flatten::FlatMap<I,U,F> as core::iter::traits::iterator::Iterator>::next
  17: kondo::main
  18: std::rt::lang_start::{{closure}}
  19: main
  20: __libc_start_main
  21: _start
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by tbillington** [comment]
That's a good point, thank you! I'll look into it.

**Comment by tbillington** [comment]
I've done a bit of restructuring on the project, part of that was refactoring how the directories are scanned.

I removed the unwrap which you were hitting, files/directories that error (for whatever reason) are now ignored. I think it would be possible to log that, potentially with some kind of verbose mode or debug mode.

Before
https://github.com/tbillington/kondo/blob/15b4502ca1fedaaec8bb7e8ad8bc01a042ffdc22/src/main.rs#L43
After
https://github.com/tbillington/kondo/blob/1108740cccc5510a2f3a4c1dadee0170a5897158/kondo-lib/src/lib.rs#L37

I'm going to close this issue because your specific error should now be resolved :)

Thank you for taking the time to raise this issue!

**Comment by senden9** [comment]
Thanks! Works now
